services:

  wa-webhook-app:
    image: canicaperu/wa-webhook-app
    container_name: wa-webhook-app
    restart: unless-stopped
    ports:
      - "${WA_WEBHOOK_PORT}:5000"
    environment:
      POSTGRES_USER: ${WA_WEBHOOK_POSTGRES_USER}
      POSTGRES_PASSWORD: ${WA_WEBHOOK_POSTGRES_PASSWORD}
      POSTGRES_DB: ${WA_WEBHOOK_POSTGRES_DB}
      WA_WEBHOOK_EVENTS: ${WA_WEBHOOK_EVENTS}
      WA_WEBHOOK_API_AUTH: ${WA_WEBHOOK_API_AUTH}
      POSTGRES_HOST: wa-webhook-db
    volumes:
      - auth:/app/.wwebjs_auth
      - cache:/app/.wwebjs_cache
    depends_on:
      wa-webhook-db:
        condition: service_healthy

  wa-webhook-db:
    image: postgres:14-alpine
    container_name: wa-webhook-db
    restart: unless-stopped
    expose:
      - 5432:5432
    environment:
      POSTGRES_USER: ${WA_WEBHOOK_POSTGRES_USER}
      POSTGRES_PASSWORD: ${WA_WEBHOOK_POSTGRES_PASSWORD}
      POSTGRES_DB: ${WA_WEBHOOK_POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${WA_WEBHOOK_POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  auth:
  cache:
  db-data: